### ISSUE TITLE
Problem with pycuda and python 3.11

### ISSUE THREAD

**Issue by easybob95** [boostorg/python#388]
Hello,

in order to test Python 3.11 with pycuda, i have just installed latest pycuda version : 2022.1

I use CUDA 11.6.2 with a windows 11 laptop.

When i try my program (using pycuda), i get this error message :

Traceback (most recent call last):
  File "D:\Alain\Astro\Soft\PC\PC_Traitement_Video_V7_51g.py", line 19, in <module>
    import pycuda.driver as drv
  File "C:\Users\apail\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycuda\driver.py", line 65, in <module>
    from pycuda._driver import *  # noqa
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

I also tried with boost.python 1.78 but i get the same issue.

Any help will be appreciate.

Alain

**Comment by inducer** [comment]
There is some possible context for the error here, particular in regard to changed requirements in Py 3.11: https://github.com/wjakob/nanobind/pull/22#discussion_r846382901

**Comment by berolinux** [comment]
https://github.com/boostorg/python/pull/385

**Comment by AlainPaillou** [comment]
Hello,

to tell the truth, i am not able to understand a single word in your responses. I am a very basic user ao Python and Pycuda.

Does your answers mean this issue will be solved in near future ?

Alain

**Comment by jakirkham** [comment]
It means there is a fix in the `develop` branch, but IIUC not in a release yet. So should be fixed in the next release.

**Comment by AlainPaillou** [comment]
Hello jakirkham,

many thx for your response. Quite a good news !

Alain
